# Generated by Django 2.0.4 on 2018-05-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
