# Generated by Django 2.0.4 on 2018-05-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180507_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Author',
            new_name='Book_Authors',
        ),
    ]
