# Generated by Django 2.0.4 on 2018-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180507_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_authors',
            name='name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
