# Generated by Django 2.0.4 on 2018-05-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180507_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Publish'),
            preserve_default=False,
        ),
    ]
