# Generated by Django 2.0.4 on 2018-05-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_authors',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book_authors',
            old_name='book',
            new_name='books',
        ),
    ]
