# Generated by Django 2.0.4 on 2018-05-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180508_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_authors',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book_authors',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book_Authors',
        ),
    ]
