# Generated by Django 2.0.5 on 2018-05-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
