# Generated by Django 2.0.5 on 2018-05-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
