# Generated by Django 2.0.5 on 2018-05-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Publish'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='app.Author'),
        ),
    ]
