# Generated by Django 2.0.5 on 2018-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180507_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
